language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  api_key:
    secure: gKK3qlvoEkevfk7AXu+comUsD7renvLZ+GA6X7vgjK5/cmS+K45Eaa41SPUUQGy3zkXTehJrYXcKd8a9yNEAjArXtwatRBamZj0CAK1pnT+WjfFXG0CmkHvkPKjO9B8nJncnvCdwoqePW/k7joQ6/uWfFKoVksbmdjZCJJ4nK9w37KwMZpgNsKq6TV5ja3Sd5tyHBNaHTOdPYkQ9y8RSuwGlUTD+P/SZUx414t2V5ArtgwghlmyX1Enj9SQGfORqkl8GZyraCx0PvRVcD29mRZoyRU5+gdXlqB3HKZvgSywc8hNXlCIf/4oLv9QSisZcJXIxncXAMdy1ce/cviS6Rr6ZSCwMV0nHqRtzt+Lp1oBWZ78DXkxzG9pqGHLaivjBrZDOq2f71w3g4Jvgv9Du4XkWpvpapXu4VJxUuzQUOuWgIAboZUanmgVU5mQ/V1m3BO+sSZt218lfh/wLdeHHedgXDkaK5L3MP+Qtfppw/2ypiZCtSFyKGJZ9SUw6xgvD/XKirTOmQxcOFjK3pDfPPdHHpIoPvh4gXOw7vphNq1u2VUjbfE4Nc0k7lHB3aYjFEAgfDl9Qq4WJAcc1h6UDDuG/wpcGqu8lYv3XrY3u6B9zzM2BtFrb2Q+LLpADOcZ6c/lxNSHGTfa+PFbs6qOBEds+I6KnLKh475N7TXyhUtU=
  app: blushing_beauty
  skip_cleanup: true
